apiVersion: v1
kind: Service
metadata:
  labels:
    app: goods
  name: goods
spec:
  ports:
  - port: 8812
    protocol: TCP
    targetPort: 8812
  selector:
    app: goods
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: goods-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: goods
    spec:
      containers:
      - name: goods
        image: 192.168.2.169/demo/goods:latest
        ports:
        - containerPort: 8812

