server:
  port: 8812
spring:
  application:
    name: goods
  datasource:
    # 数据库名
    name: test
    url: jdbc:mysql://192.168.2.169:3306/${spring.datasource.name}?serverTimezone=GMT%2B8
    username: root
    password: aA111111
    driver-class-name: com.mysql.jdbc.Driver


# 配置注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS}:8761/eureka/
  instance:
    prefer-ip-address: true

